/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pychamciav2;

import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Pieter Struwig
 */
public class home extends javax.swing.JFrame {

    private SpinnerNumberModel boutsdata;

    /**
     * Creates new form NewJFrame
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        homepage = new javax.swing.JPanel();
        addmember = new javax.swing.JButton();
        selectmember = new javax.swing.JComboBox<>();
        title = new javax.swing.JLabel();
        infopagemain = new javax.swing.JTextArea();
        addmemberpage = new javax.swing.JPanel();
        homebutton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        noofbouts = new javax.swing.JLabel();
        namemember = new javax.swing.JTextField();
        boutsdata = new SpinnerNumberModel(spinnerValue,spinnerMin,spinnerMax,spinnerInterval);
        noboutsmember = new javax.swing.JSpinner(boutsdata);
        weightmember = new javax.swing.JTextField();
        kgs = new javax.swing.JLabel();
        dateofbirthmember = new javax.swing.JTextField();
        ddmmyyyy = new javax.swing.JLabel();
        savemember = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        homepage2 = new javax.swing.JPanel();
        memberparent = new javax.swing.JTabbedPane();
        memberhome = new javax.swing.JPanel();
        loggedinas = new javax.swing.JLabel();
        currentmember = new javax.swing.JTextField();
        agemember = new javax.swing.JLabel();
        weightmember1 = new javax.swing.JLabel();
        noofbouts1 = new javax.swing.JLabel();
        joineddate = new javax.swing.JLabel();
        editmemberdata = new javax.swing.JButton();
        homebutton3 = new javax.swing.JButton();
        ageofmember = new javax.swing.JTextField();
        weightofmember = new javax.swing.JTextField();
        noofboutsofmember = new javax.swing.JTextField();
        joineddatemember = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        enterdatamain = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        enterbutton3 = new javax.swing.JButton();
        viewdatamain = new javax.swing.JPanel();
        viewdataselection = new javax.swing.JPanel();
        viewdataoverall1 = new javax.swing.JButton();
        viewdataspecificbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        viewdataspecificdate = new javax.swing.JPanel();
        returnbutton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewdataoverall = new javax.swing.JPanel();
        returnbutton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        editentereddata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parent.setLayout(new java.awt.CardLayout());

        homepage.setPreferredSize(new java.awt.Dimension(613, 450));

        addmember.setText("Add Member");
        addmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemberActionPerformed(evt);
            }
        });

        selectmember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Member" }));
        selectmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectmemberActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Pychamcia");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        infopagemain.setEditable(false);
        infopagemain.setColumns(20);
        infopagemain.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        infopagemain.setRows(5);
        infopagemain.setText("This program is for storing the data that is gathered from the Hykso \nprogram. The purpose of the program is to make the data that is \nentered easily accessible and viewable. ");
        infopagemain.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        infopagemain.setSelectionColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout homepageLayout = new javax.swing.GroupLayout(homepage);
        homepage.setLayout(homepageLayout);
        homepageLayout.setHorizontalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addmember, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(title))
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(infopagemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        homepageLayout.setVerticalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepageLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(infopagemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectmember, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addmember, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        Parent.add(homepage, "card2");

        addmemberpage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        homebutton1.setText("Home");
        homebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton1ActionPerformed(evt);
            }
        });

        name.setText("Name");

        dateofbirth.setText("Date of birth");

        weight.setText("Weight");

        noofbouts.setText("No. of bouts");

        namemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namememberActionPerformed(evt);
            }
        });

        weightmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightmemberActionPerformed(evt);
            }
        });

        kgs.setText("Kgs");

        dateofbirthmember.setToolTipText("");
        dateofbirthmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofbirthmemberActionPerformed(evt);
            }
        });

        ddmmyyyy.setText("DD/MM/YYYY");

        savemember.setText("Save");
        savemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savememberActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Add Member");

        javax.swing.GroupLayout addmemberpageLayout = new javax.swing.GroupLayout(addmemberpage);
        addmemberpage.setLayout(addmemberpageLayout);
        addmemberpageLayout.setHorizontalGroup(
            addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmemberpageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                        .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(noofbouts)
                                    .addComponent(weight)
                                    .addComponent(dateofbirth))
                                .addGap(37, 37, 37)
                                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namemember)
                                    .addGroup(addmemberpageLayout.createSequentialGroup()
                                        .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(addmemberpageLayout.createSequentialGroup()
                                                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(weightmember)
                                                    .addComponent(dateofbirthmember, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(addmemberpageLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ddmmyyyy))
                                                    .addGroup(addmemberpageLayout.createSequentialGroup()
                                                        .addGap(44, 44, 44)
                                                        .addComponent(kgs))))
                                            .addComponent(noboutsmember, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 286, Short.MAX_VALUE)))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(savemember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homebutton1)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(199, 199, 199))))
        );
        addmemberpageLayout.setVerticalGroup(
            addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(79, 79, 79)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(namemember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateofbirth)
                    .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateofbirthmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddmmyyyy)))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight)
                    .addComponent(weightmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgs))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noofbouts)
                    .addComponent(noboutsmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebutton1)
                    .addComponent(savemember))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        Parent.add(addmemberpage, "card3");

        loggedinas.setText("Logged in as: ");

        currentmember.setEditable(false);
        currentmember.setText("jTextField1");

        agemember.setText("Age");

        weightmember1.setText("Weight");

        noofbouts1.setText("# of Bouts");

        joineddate.setText("Joined Date");

        editmemberdata.setText("Edit Member Data");
        editmemberdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmemberdataActionPerformed(evt);
            }
        });

        homebutton3.setText("Switch member");
        homebutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton3ActionPerformed(evt);
            }
        });

        ageofmember.setEditable(false);
        ageofmember.setText("jTextField1");

        weightofmember.setEditable(false);
        weightofmember.setText("jTextField1");

        noofboutsofmember.setEditable(false);
        noofboutsofmember.setText("jTextField1");

        joineddatemember.setEditable(false);
        joineddatemember.setText("jTextField1");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Home");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberhomeLayout = new javax.swing.GroupLayout(memberhome);
        memberhome.setLayout(memberhomeLayout);
        memberhomeLayout.setHorizontalGroup(
            memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberhomeLayout.createSequentialGroup()
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberhomeLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(memberhomeLayout.createSequentialGroup()
                                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberhomeLayout.createSequentialGroup()
                                        .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agemember)
                                            .addComponent(weightmember1))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberhomeLayout.createSequentialGroup()
                                        .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(noofbouts1)
                                                .addComponent(joineddate))
                                            .addComponent(loggedinas, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)))
                                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(joineddatemember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noofboutsofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weightofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(editmemberdata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homebutton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(memberhomeLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel11)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        memberhomeLayout.setVerticalGroup(
            memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberhomeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(53, 53, 53)
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedinas)
                    .addComponent(currentmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agemember)
                    .addComponent(ageofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightmember1)
                    .addComponent(weightofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noofbouts1)
                    .addComponent(noofboutsofmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(memberhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joineddate)
                    .addComponent(joineddatemember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(editmemberdata)
                .addGap(18, 18, 18)
                .addComponent(homebutton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        memberparent.addTab("Home", memberhome);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField1");

        jTextField3.setText("jTextField1");

        jTextField4.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField1");

        jTextField8.setText("jTextField1");

        jTextField9.setText("jTextField1");

        jLabel5.setText("Round 1");

        jLabel6.setText("Round 2");

        jLabel7.setText("Round 3");

        jLabel8.setText("Punch Power");

        jLabel9.setText("Punch Count");

        jLabel10.setText("Intensity");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("Enter Data");

        enterbutton3.setText("Enter");

        javax.swing.GroupLayout enterdatamainLayout = new javax.swing.GroupLayout(enterdatamain);
        enterdatamain.setLayout(enterdatamainLayout);
        enterdatamainLayout.setHorizontalGroup(
            enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdatamainLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enterdatamainLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterdatamainLayout.createSequentialGroup()
                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(enterdatamainLayout.createSequentialGroup()
                                .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterdatamainLayout.createSequentialGroup()
                                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterdatamainLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(27, 27, 27)))
                                .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(enterdatamainLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterdatamainLayout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterdatamainLayout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enterbutton3)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        enterdatamainLayout.setVerticalGroup(
            enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterdatamainLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12)
                .addGap(114, 114, 114)
                .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enterdatamainLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enterdatamainLayout.createSequentialGroup()
                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(enterdatamainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(54, 54, 54)
                .addComponent(enterbutton3)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        memberparent.addTab("Enter Data ", enterdatamain);

        viewdatamain.setLayout(new java.awt.CardLayout());

        viewdataoverall1.setText("overall");
        viewdataoverall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdataoverall1ActionPerformed(evt);
            }
        });

        viewdataspecificbutton.setText("Specific");
        viewdataspecificbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdataspecificbuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("View Data Selection");

        javax.swing.GroupLayout viewdataselectionLayout = new javax.swing.GroupLayout(viewdataselection);
        viewdataselection.setLayout(viewdataselectionLayout);
        viewdataselectionLayout.setHorizontalGroup(
            viewdataselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataselectionLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(viewdataselectionLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(viewdataselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewdataoverall1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(viewdataspecificbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewdataselectionLayout.setVerticalGroup(
            viewdataselectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataselectionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addComponent(viewdataspecificbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewdataoverall1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        viewdatamain.add(viewdataselection, "card2");

        returnbutton2.setText("Return");
        returnbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbutton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("View Data Specific Date");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout viewdataspecificdateLayout = new javax.swing.GroupLayout(viewdataspecificdate);
        viewdataspecificdate.setLayout(viewdataspecificdateLayout);
        viewdataspecificdateLayout.setHorizontalGroup(
            viewdataspecificdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewdataspecificdateLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(viewdataspecificdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataspecificdateLayout.createSequentialGroup()
                        .addGroup(viewdataspecificdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnbutton2))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataspecificdateLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        viewdataspecificdateLayout.setVerticalGroup(
            viewdataspecificdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewdataspecificdateLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnbutton2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        viewdatamain.add(viewdataspecificdate, "card4");

        returnbutton1.setText("Return");
        returnbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbutton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("View Data Overall ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        editentereddata.setText("Edit Data");

        javax.swing.GroupLayout viewdataoverallLayout = new javax.swing.GroupLayout(viewdataoverall);
        viewdataoverall.setLayout(viewdataoverallLayout);
        viewdataoverallLayout.setHorizontalGroup(
            viewdataoverallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewdataoverallLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataoverallLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(viewdataoverallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataoverallLayout.createSequentialGroup()
                        .addComponent(editentereddata, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnbutton1)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewdataoverallLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(145, 145, 145))))
        );
        viewdataoverallLayout.setVerticalGroup(
            viewdataoverallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewdataoverallLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(viewdataoverallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnbutton1)
                    .addComponent(editentereddata))
                .addGap(30, 30, 30))
        );

        viewdatamain.add(viewdataoverall, "card3");

        memberparent.addTab(" View Data", viewdatamain);

        javax.swing.GroupLayout homepage2Layout = new javax.swing.GroupLayout(homepage2);
        homepage2.setLayout(homepage2Layout);
        homepage2Layout.setHorizontalGroup(
            homepage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberparent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        homepage2Layout.setVerticalGroup(
            homepage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepage2Layout.createSequentialGroup()
                .addComponent(memberparent, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Parent.add(homepage2, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemberActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(addmemberpage);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_addmemberActionPerformed

    private void homebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton1ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_homebutton1ActionPerformed

    private void namememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namememberActionPerformed

    private void weightmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightmemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightmemberActionPerformed

    private void savememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savememberActionPerformed
        // TODO add your handling code here:                  
        int count = selectmember.getItemCount();
        ArrayList<String> builder;
        builder = new ArrayList<>();
        for (int i = 0; i < count; i++) {
                builder.add(selectmember.getItemAt(i));
                if (i < count - 1) {
                    
                }
            }
        builder.add (namemember.getText());
        builder.add (weightmember.getText());
        builder.add (noofbouts.getText());
        builder.add (dateofbirthmember.getText());
        
        StringBuilder data = new StringBuilder(); 
        for (String s : builder){
            data.append(s);
            
        }
 
        
        selectmember.setModel(new javax.swing.DefaultComboBoxModel<>(data));

    }//GEN-LAST:event_savememberActionPerformed

    private void selectmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectmemberActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(homepage2);
        Parent.repaint();
        Parent.revalidate();   
    }//GEN-LAST:event_selectmemberActionPerformed

    private void editmemberdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmemberdataActionPerformed
        // TODO add your handling code here:
        ageofmember.setEditable(true); 
        weightofmember.setEditable(true); 
        
        
    }//GEN-LAST:event_editmemberdataActionPerformed

    private void homebutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton3ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_homebutton3ActionPerformed

    private void viewdataoverall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdataoverall1ActionPerformed
        // TODO add your handling code here:
        viewdatamain.removeAll();
        viewdatamain.add(viewdataoverall);
        viewdatamain.repaint();
        viewdatamain.revalidate();
    }//GEN-LAST:event_viewdataoverall1ActionPerformed

    private void returnbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbutton1ActionPerformed
        // TODO add your handling code here:
        viewdatamain.removeAll();
        viewdatamain.add(viewdataselection);
        viewdatamain.repaint();
        viewdatamain.revalidate();
    }//GEN-LAST:event_returnbutton1ActionPerformed

    private void viewdataspecificbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdataspecificbuttonActionPerformed
        // TODO add your handling code here:
        viewdatamain.removeAll();
        viewdatamain.add(viewdataspecificdate);
        viewdatamain.repaint();
        viewdatamain.revalidate();
    }//GEN-LAST:event_viewdataspecificbuttonActionPerformed

    private void returnbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbutton2ActionPerformed
        // TODO add your handling code here:
        viewdatamain.removeAll();
        viewdatamain.add(viewdataselection);
        viewdatamain.repaint();
        viewdatamain.revalidate();
    }//GEN-LAST:event_returnbutton2ActionPerformed

    private void dateofbirthmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofbirthmemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthmemberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JButton addmember;
    private javax.swing.JPanel addmemberpage;
    private javax.swing.JLabel agemember;
    private javax.swing.JTextField ageofmember;
    private javax.swing.JTextField currentmember;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JTextField dateofbirthmember;
    private javax.swing.JLabel ddmmyyyy;
    private javax.swing.JButton editentereddata;
    private javax.swing.JButton editmemberdata;
    private javax.swing.JButton enterbutton3;
    private javax.swing.JPanel enterdatamain;
    private javax.swing.JButton homebutton1;
    private javax.swing.JButton homebutton3;
    private javax.swing.JPanel homepage;
    private javax.swing.JPanel homepage2;
    private javax.swing.JTextArea infopagemain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel joineddate;
    private javax.swing.JTextField joineddatemember;
    private javax.swing.JLabel kgs;
    private javax.swing.JLabel loggedinas;
    private javax.swing.JPanel memberhome;
    private javax.swing.JTabbedPane memberparent;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namemember;
    private javax.swing.JSpinner noboutsmember;
    private javax.swing.JLabel noofbouts;
    private javax.swing.JLabel noofbouts1;
    private javax.swing.JTextField noofboutsofmember;
    private javax.swing.JButton returnbutton1;
    private javax.swing.JButton returnbutton2;
    private javax.swing.JButton savemember;
    private javax.swing.JComboBox<String> selectmember;
    private javax.swing.JLabel title;
    private javax.swing.JPanel viewdatamain;
    private javax.swing.JPanel viewdataoverall;
    private javax.swing.JButton viewdataoverall1;
    private javax.swing.JPanel viewdataselection;
    private javax.swing.JButton viewdataspecificbutton;
    private javax.swing.JPanel viewdataspecificdate;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weightmember;
    private javax.swing.JLabel weightmember1;
    private javax.swing.JTextField weightofmember;
    // End of variables declaration//GEN-END:variables
    // Own Variables 
    private     Integer     spinnerMax = 999;
    private     Integer     spinnerMin = 0;
    private     Integer     spinnerInterval = 1;
    private     Integer     spinnerValue = 0;
}

