/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pychamciav2;

/**
 *
 * @author Pieter Struwig
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        homepage = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        addmemberpage = new javax.swing.JPanel();
        homebutton1 = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        noofbouts = new javax.swing.JLabel();
        namemember = new javax.swing.JTextField();
        noboutsmember = new javax.swing.JSpinner();
        weightmember = new javax.swing.JTextField();
        kgs = new javax.swing.JLabel();
        dateofbirthmember = new javax.swing.JTextField();
        ddmmyyyy = new javax.swing.JLabel();
        savemember = new javax.swing.JButton();
        homepage2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Parent.setLayout(new java.awt.CardLayout());

        jButton1.setText("Add Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Member", "Johan", "Lucan", "Caleb", "James" }));

        javax.swing.GroupLayout homepageLayout = new javax.swing.GroupLayout(homepage);
        homepage.setLayout(homepageLayout);
        homepageLayout.setHorizontalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        homepageLayout.setVerticalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepageLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        Parent.add(homepage, "card2");

        homebutton1.setText("Home");
        homebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebutton1ActionPerformed(evt);
            }
        });

        name.setText("Name");

        dateofbirth.setText("Date of birth");

        weight.setText("Weight");

        noofbouts.setText("No. of bouts");

        namemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namememberActionPerformed(evt);
            }
        });

        weightmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightmemberActionPerformed(evt);
            }
        });

        kgs.setText("Kgs");

        dateofbirthmember.setToolTipText("");

        ddmmyyyy.setText("DD/MM/YYYY");

        savemember.setText("Save");
        savemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savememberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addmemberpageLayout = new javax.swing.GroupLayout(addmemberpage);
        addmemberpage.setLayout(addmemberpageLayout);
        addmemberpageLayout.setHorizontalGroup(
            addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addmemberpageLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(noofbouts)
                            .addComponent(weight)
                            .addComponent(dateofbirth))
                        .addGap(37, 37, 37)
                        .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namemember)
                            .addGroup(addmemberpageLayout.createSequentialGroup()
                                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noboutsmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addmemberpageLayout.createSequentialGroup()
                                        .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(weightmember, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(dateofbirthmember))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ddmmyyyy)))
                                .addGap(25, 25, 25))))
                    .addGroup(addmemberpageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kgs)
                        .addGap(63, 63, 63)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savemember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homebutton1)
                .addGap(22, 22, 22))
        );
        addmemberpageLayout.setVerticalGroup(
            addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmemberpageLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(namemember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateofbirth)
                    .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateofbirthmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddmmyyyy)))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight)
                    .addComponent(weightmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgs))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noofbouts)
                    .addComponent(noboutsmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addmemberpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebutton1)
                    .addComponent(savemember))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Parent.add(addmemberpage, "card3");

        jTabbedPane1.addTab("Enter data", jTabbedPane2);
        jTabbedPane1.addTab("Edit data", jTabbedPane3);
        jTabbedPane1.addTab("View data", jTabbedPane4);

        javax.swing.GroupLayout homepage2Layout = new javax.swing.GroupLayout(homepage2);
        homepage2.setLayout(homepage2Layout);
        homepage2Layout.setHorizontalGroup(
            homepage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        homepage2Layout.setVerticalGroup(
            homepage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        Parent.add(homepage2, "card4");

        getContentPane().add(Parent);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(addmemberpage);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebutton1ActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(homepage);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_homebutton1ActionPerformed

    private void namememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namememberActionPerformed

    private void weightmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightmemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightmemberActionPerformed

    private void savememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savememberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel addmemberpage;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JTextField dateofbirthmember;
    private javax.swing.JLabel ddmmyyyy;
    private javax.swing.JButton homebutton1;
    private javax.swing.JPanel homepage;
    private javax.swing.JPanel homepage2;
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel kgs;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namemember;
    private javax.swing.JSpinner noboutsmember;
    private javax.swing.JLabel noofbouts;
    private javax.swing.JButton savemember;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weightmember;
    // End of variables declaration//GEN-END:variables
}
